# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oq80CdBdcbUD0oWSnURi-28i22gS9an9
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

path="/student-mat.csv"
df=pd.read_csv(path,sep=";")

df.head(5)

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

corr=df.select_dtypes(include="number").corr()

plt.figure(figsize=(10,10))
sns.heatmap(corr,annot=True,cmap="coolwarm")
plt.plot()

objects=df.select_dtypes(include="object")
objects

for i in objects.columns:
    print(f"{i}: {df[i].nunique()}")

df=pd.get_dummies(
    df,
    columns=objects.columns,
    drop_first=True,
    dtype=int
)
df.head(5)

df.info()

df.to_csv("student-mat-cleaned.csv", index=False)
